/* SPDX-License-Identifier: Apache-2.0 */
/**
 * Property-based tests for the SSE parser inside useSubSessionSSE.
 *
 * Two invariants are asserted over all generated byte sequences:
 *   1. The state machine never crashes on arbitrary byte input.
 *   2. Every well-formed event (event:NAME\ndata:JSON\n\n) is delivered
 *      exactly once — never dropped due to chunk boundary splits.
 *
 * Strategy: we replicate the hook's exact parsing loop as a pure function
 * (same code, zero React dependency) so fast-check can explore hundreds of
 * inputs without renderHook / DOM overhead. The integration between the parser
 * and React state is covered by the deterministic tests in
 * test_useSubSessionSSE.spec.ts.
 *
 * fast-check generates arbitrary byte sequences — the chunk-boundary split
 * is the exact bug class fixed in Fix #1.
 */
import { describe, it, expect } from "vitest";
import * as fc from "fast-check";

// ─── Inline SSE parser (mirrors useSubSessionSSE's loop) ─────────────────────
//
// This is NOT a copy-paste that drifts from production. It mirrors the exact
// three-state machine (buf accumulation → line split → eventType carry-over →
// data dispatch) from the hook. If the hook's parsing logic changes, update
// this mirror. The parser is extracted here purely to avoid DOM overhead
// inside the property loop.

interface ParsedEvent {
  type: string;
  rawData: string;
  /** True if JSON.parse succeeded */
  valid: boolean;
}

/**
 * parseSseChunks — run the hook's SSE parsing loop over an array of raw byte
 * chunks. Returns:
 *   - events: list of events dispatched (in order)
 *   - crashed: true if the loop threw an uncaught exception
 */
function parseSseChunks(chunks: readonly Uint8Array[]): {
  events: ParsedEvent[];
  crashed: boolean;
  buf: string;
} {
  const decoder = new TextDecoder();
  let buf = "";
  let eventType = "";
  const events: ParsedEvent[] = [];

  try {
    for (const chunk of chunks) {
      buf += decoder.decode(chunk, { stream: true });

      const lines = buf.split("\n");
      buf = lines.pop() ?? "";

      for (const line of lines) {
        if (line.startsWith("event: ")) {
          eventType = line.slice(7).trim();
        } else if (line.startsWith("data: ")) {
          const raw = line.slice(6).trim();
          if (!raw) continue;
          let valid = false;
          try {
            JSON.parse(raw);
            valid = true;
          } catch {
            // invalid JSON — still counts as dispatched
          }
          events.push({ type: eventType, rawData: raw, valid });
        } else if (line === "") {
          // SSE event terminator — reset eventType
          eventType = "";
        }
      }
    }
    // flush remaining buf (mirrors decoder.decode() at end of stream)
    return { events, crashed: false, buf };
  } catch (err) {
    return { events, crashed: true, buf };
  }
}

// ─── Arbitraries ──────────────────────────────────────────────────────────────

const encoder = new TextEncoder();

/**
 * arb_byte_chunk — random Uint8Array of 0–200 bytes, biased towards printable
 * ASCII so some runs accidentally form partial SSE frames.
 */
const arb_byte_chunk = fc
  .uint8Array({ minLength: 0, maxLength: 200 })
  .map((arr) => new Uint8Array(arr));

/**
 * arb_chunk_list — list of 0–20 raw byte chunks.
 */
const arb_chunk_list = fc.array(arb_byte_chunk, {
  minLength: 0,
  maxLength: 20,
});

/**
 * Split a Uint8Array at the given byte offsets.
 */
function splitAt(bytes: Uint8Array, positions: number[]): Uint8Array[] {
  const sorted = [...new Set(positions)].sort((a, b) => a - b);
  const result: Uint8Array[] = [];
  let prev = 0;
  for (const pos of sorted) {
    if (pos > prev && pos < bytes.length) {
      result.push(bytes.slice(prev, pos));
      prev = pos;
    }
  }
  if (prev < bytes.length) result.push(bytes.slice(prev));
  return result.filter((c) => c.length > 0);
}

/**
 * Build N deterministic sub.delta frames followed by sub.complete.
 */
function buildDeltaPayload(deltas: string[]): string {
  const deltaFrames = deltas
    .map((d) => `event: sub.delta\ndata: ${JSON.stringify({ delta: d })}\n\n`)
    .join("");
  const completeFrame = `event: sub.complete\ndata: ${JSON.stringify({ final_content: deltas.join("") })}\n\n`;
  return deltaFrames + completeFrame;
}

// ─── Invariant 1: No crashes on arbitrary byte input ─────────────────────────

describe("SSE parser property — Invariant 1: never crashes on arbitrary input", () => {
  it("parseSseChunks never throws over arbitrary byte sequences", () => {
    fc.assert(
      fc.property(arb_chunk_list, (chunks) => {
        const { crashed } = parseSseChunks(chunks);
        // Invariant: the parser must not throw
        expect(crashed).toBe(false);
      }),
      {
        numRuns: 5000,
        seed: 0xca7b_eef0,
      },
    );
  });

  it("parseSseChunks always returns a stable events array on arbitrary input", () => {
    fc.assert(
      fc.property(arb_chunk_list, (chunks) => {
        const { events, crashed } = parseSseChunks(chunks);
        expect(crashed).toBe(false);
        // events is always an array (never undefined / null)
        expect(Array.isArray(events)).toBe(true);
        // every event always has type and rawData as strings
        for (const evt of events) {
          expect(typeof evt.type).toBe("string");
          expect(typeof evt.rawData).toBe("string");
        }
      }),
      {
        numRuns: 5000,
        seed: 0xbeef_cafe,
      },
    );
  });
});

// ─── Invariant 2: Valid events delivered exactly once ─────────────────────────

describe("SSE parser property — Invariant 2: valid events never dropped across chunk boundaries", () => {
  it("all sub.delta events delivered regardless of split position — Fix #1 regression", () => {
    /**
     * Build a deterministic payload with N deltas. Split at arbitrary positions.
     * Assert the parser sees exactly N sub.delta events with valid JSON.
     *
     * Fix #1 bug: eventType reset inside the read-loop caused the data: line
     * to be dispatched under eventType="" when a chunk boundary fell between
     * the event: line and its data: line. The replicated parser hoists
     * eventType outside the loop — same fix as the hook.
     */
    fc.assert(
      fc.property(
        fc.array(
          fc.string({ minLength: 1, maxLength: 30, unit: "grapheme-ascii" }),
          { minLength: 1, maxLength: 8 },
        ),
        fc.array(fc.integer({ min: 1, max: 999 }), {
          minLength: 0,
          maxLength: 12,
        }),
        (deltas, rawPositions) => {
          const payload = buildDeltaPayload(deltas);
          const bytes = encoder.encode(payload);

          // Scale positions to byte range.
          const positions = rawPositions
            .map((p) => Math.round((p / 1000) * bytes.length))
            .filter((p) => p >= 1 && p < bytes.length);

          const chunks = positions.length > 0 ? splitAt(bytes, positions) : [bytes];
          const { events, crashed } = parseSseChunks(chunks);

          expect(crashed).toBe(false);

          // Count sub.delta events with valid JSON data.
          const deltaEvents = events.filter((e) => e.type === "sub.delta" && e.valid);
          // Each delta must be delivered exactly once.
          expect(deltaEvents.length).toBe(deltas.length);

          // Verify the actual delta values match (order preserved).
          const deliveredDeltas = deltaEvents.map((e) => {
            const obj = JSON.parse(e.rawData) as { delta?: string };
            return obj.delta ?? "";
          });
          expect(deliveredDeltas).toEqual(deltas);
        },
      ),
      {
        numRuns: 3000,
        seed: 0xf01d_b4be,
      },
    );
  });

  it("sub.complete event always delivered at end regardless of split position", () => {
    fc.assert(
      fc.property(
        fc.array(fc.integer({ min: 1, max: 999 }), {
          minLength: 0,
          maxLength: 20,
        }),
        (rawPositions) => {
          const payload = `event: sub.complete\ndata: ${JSON.stringify({ final_content: "ok" })}\n\n`;
          const bytes = encoder.encode(payload);

          const positions = rawPositions
            .map((p) => Math.round((p / 1000) * bytes.length))
            .filter((p) => p >= 1 && p < bytes.length);

          const chunks = positions.length > 0 ? splitAt(bytes, positions) : [bytes];
          const { events, crashed } = parseSseChunks(chunks);

          expect(crashed).toBe(false);

          const completeEvents = events.filter(
            (e) => e.type === "sub.complete" && e.valid,
          );
          // sub.complete must appear exactly once
          expect(completeEvents.length).toBe(1);
        },
      ),
      {
        numRuns: 3000,
        seed: 0x55e_7c0de,
      },
    );
  });

  it("event type is never inherited across the frame terminator (empty line resets it)", () => {
    /**
     * If eventType is not reset on the empty-line terminator, a later
     * data: line with no preceding event: line would inherit the previous
     * event's type — a false delivery. Assert this never happens.
     */
    fc.assert(
      fc.property(
        // Two sequential frames with different types.
        fc.tuple(
          fc.constantFrom("sub.delta", "sub.error", "sub.complete", "sub.reasoning.start"),
          fc.constantFrom("sub.delta", "sub.error", "sub.complete", "sub.reasoning.end"),
        ),
        fc.array(fc.integer({ min: 1, max: 999 }), { minLength: 0, maxLength: 10 }),
        ([type1, type2], rawPositions) => {
          const payload =
            `event: ${type1}\ndata: ${JSON.stringify({ x: 1 })}\n\n` +
            `event: ${type2}\ndata: ${JSON.stringify({ x: 2 })}\n\n`;
          const bytes = encoder.encode(payload);

          const positions = rawPositions
            .map((p) => Math.round((p / 1000) * bytes.length))
            .filter((p) => p >= 1 && p < bytes.length);

          const chunks = positions.length > 0 ? splitAt(bytes, positions) : [bytes];
          const { events } = parseSseChunks(chunks);

          // Should be exactly 2 events dispatched, in order.
          expect(events.length).toBe(2);
          expect(events[0]?.type).toBe(type1);
          expect(events[1]?.type).toBe(type2);
        },
      ),
      {
        numRuns: 2000,
        seed: 0xdead_c0de,
      },
    );
  });
});
