# SPDX-License-Identifier: Apache-2.0
"""Test-data generators for the P14 stress harness.

- ``realistic`` — Faker-backed realistic chat titles / usernames / messages.
- ``adversarial`` — Hypothesis strategies for Unicode RTL / NUL / oversized
  payloads / SQL injection probes / path-traversal probes.

A pre-recorded corpus of 100 sanitised synthetic transcripts lives at
``tests/stress/corpus/transcripts.jsonl`` (generated by
``data/build_corpus.py`` at install time; committed to keep runs
deterministic).
"""
