# SPDX-License-Identifier: Apache-2.0
"""Generate the 100-transcript synthetic corpus used by 10% of scenarios.

The corpus mix across scenarios: 60% Faker / 30% Hypothesis / 10%
pre-recorded corpus from ``tests/stress/corpus/`` (sanitized real chat
transcripts).

We do NOT use real admin chat data — these transcripts are entirely
synthetic.  Instead we synthesise 100 plausible transcripts using Faker.
Each transcript is a list of
``{role, content}`` dicts spanning 2–10 turns.

The output JSONL is committed to ``tests/stress/corpus/transcripts.jsonl``
so test runs are reproducible without regenerating.  Re-run this
module to refresh the corpus (e.g. after Faker version bump).

Usage:
    uv run python -m tests.stress.data.build_corpus
"""
from __future__ import annotations

import json
import random
from pathlib import Path

from .realistic import FAKER, realistic_chat_title, realistic_user_message


def build_transcript(min_turns: int = 2, max_turns: int = 10) -> dict[str, object]:
    """Return one synthetic transcript.

    Shape::

        {
            "title": "...",
            "turns": [
                {"role": "user", "content": "..."},
                {"role": "assistant", "content": "..."},
                ...
            ]
        }

    The assistant turns are Faker paragraphs — not actually generated by
    a model, just plausible-shaped text for upload into chat messages.
    """
    turn_count = random.randint(min_turns, max_turns)
    if turn_count % 2 == 1:
        # Always close with an assistant reply.
        turn_count += 1
    turns: list[dict[str, str]] = []
    for i in range(turn_count):
        if i % 2 == 0:
            turns.append({"role": "user", "content": realistic_user_message()})
        else:
            turns.append(
                {
                    "role": "assistant",
                    "content": FAKER.paragraph(nb_sentences=random.randint(2, 6)),
                }
            )
    return {"title": realistic_chat_title(), "turns": turns}


def main(out_path: Path | None = None, count: int = 100) -> Path:
    """Generate ``count`` transcripts to ``out_path``.

    Args:
        out_path: Destination JSONL.  Defaults to
            ``tests/stress/corpus/transcripts.jsonl``.
        count:    How many transcripts to write.

    Returns:
        The absolute path written.
    """
    if out_path is None:
        out_path = Path(__file__).resolve().parents[1] / "corpus" / "transcripts.jsonl"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # Stable seed so reruns produce the same content.
    random.seed(1742)
    FAKER.seed_instance(1742)
    with out_path.open("w", encoding="utf-8") as fh:
        for _ in range(count):
            fh.write(json.dumps(build_transcript(), ensure_ascii=False) + "\n")
    return out_path


if __name__ == "__main__":
    path = main()
    print(f"corpus written: {path}")
